<?php
use Sulu\Component\Localization\Localization;
use Sulu\Component\Webspace\Manager\WebspaceCollection;
use Sulu\Component\Webspace\Portal;
use Sulu\Component\Webspace\PortalInformation;
use Sulu\Component\Webspace\Theme;
use Sulu\Component\Webspace\Environment;
use Sulu\Component\Webspace\Security;
use Sulu\Component\Webspace\Segment;
use Sulu\Component\Webspace\Url;
use Sulu\Component\Webspace\CustomUrl;
use Sulu\Component\Webspace\Webspace;
use Sulu\Component\Webspace\Navigation;
use Sulu\Component\Webspace\NavigationContext;

/**
 * WebspaceCollectionCache
 *
 * DO NOT EDIT
 * This file is autogenerated by the Sulu Webspace component
 */
class WebspaceCollectionCache extends WebspaceCollection
{
    public function __construct()
    {
        $webspaceRefs = array();
        $portalRefs = array();
        $localizationRefs = array();
        $segmentRefs = array();
        $portalInformationRefs = array();

        // new webspace
        $webspace = new Webspace();
        $webspace->setKey('sulu_io');
        $webspace->setName('sulu.io');
        // add localization to webspace
        $localization0 = new Localization();
        $localization0->setLanguage('en');
        $localization0->setCountry('');
        $localization0->setShadow('');
        $localization0->setDefault('1');
        $localization0->setXDefault('');
        $localizationRefs['sulu_io_en'] = $localization0;
        $webspace->addLocalization($localization0);
        // add localization to webspace
        $localization0 = new Localization();
        $localization0->setLanguage('de');
        $localization0->setCountry('');
        $localization0->setShadow('');
        $localization0->setDefault('');
        $localization0->setXDefault('');
        $localizationRefs['sulu_io_de'] = $localization0;
        $webspace->addLocalization($localization0);
        // add theme
        $theme = new Theme();
        $theme->setKey('default');
        $theme->addErrorTemplate('default', 'ClientWebsiteBundle:views:error.html.twig');
        $theme->addErrorTemplate(404, 'ClientWebsiteBundle:views:error404.html.twig');
        $theme->addDefaultTemplate('page', 'default');
        $theme->addDefaultTemplate('homepage', 'overview');
        $webspace->setTheme($theme);

        // add navigation
        $navigation = new Navigation();
        $navigation->addContext(new NavigationContext('main',     array(
                        'title' =>     array(
                        'de' => 'Hauptnavigation',
                                'en' => 'Mainnavigation',
                )
,
                )
));
        $webspace->setNavigation($navigation);


        // new portal
        $portal = new Portal();
        $portal->setName('sulu.io');
        $portal->setKey('sulu_io');
        $portal->setResourceLocatorStrategy('tree');
        $portal->setWebspace($webspace);

        // add localization
        $localization = new Localization();
        $localization->setLanguage('en');
        $localization->setCountry('');
        $localization->setDefault('1');
        $localization->setXDefault('');
        $portal->addLocalization($localization);

        // add localization
        $localization = new Localization();
        $localization->setLanguage('de');
        $localization->setCountry('');
        $localization->setDefault('');
        $localization->setXDefault('');
        $portal->addLocalization($localization);


        // add environment
        $environment = new Environment();
        $environment->setType('prod');

        // add environment url
        $url = new Url();
        $url->setUrl('sulu.lo/{localization}');
        $url->setLanguage('');
        $url->setCountry('');
        $url->setSegment('');
        $url->setRedirect('');
        $url->setMain(true);
        $url->setAnalyticsKey('');
        $environment->addUrl($url);

        $portal->addEnvironment($environment);

        // add environment
        $environment = new Environment();
        $environment->setType('stage');

        // add environment url
        $url = new Url();
        $url->setUrl('sulu.lo/{localization}');
        $url->setLanguage('');
        $url->setCountry('');
        $url->setSegment('');
        $url->setRedirect('');
        $url->setMain(true);
        $url->setAnalyticsKey('');
        $environment->addUrl($url);

        $portal->addEnvironment($environment);

        // add environment
        $environment = new Environment();
        $environment->setType('dev');

        // add environment url
        $url = new Url();
        $url->setUrl('sulu.lo/{localization}');
        $url->setLanguage('');
        $url->setCountry('');
        $url->setSegment('');
        $url->setRedirect('');
        $url->setMain(true);
        $url->setAnalyticsKey('');
        $environment->addUrl($url);

        $portal->addEnvironment($environment);
        $portalRefs['sulu_io'] = $portal;
        $webspace->addPortal($portal);

        $webspaceRefs['sulu_io'] = $webspace;



        $portalInformationRefs['prod']['sulu.lo/en'] = new PortalInformation(
            1,
            $webspaceRefs['sulu_io'],
            $portalRefs['sulu_io'],
            $localizationRefs['sulu_io_en'],
            'sulu.lo/en',
            null,
            null,
            null,
            true,
            'sulu.lo/{localization}',
            10
        );

        $portalInformationRefs['prod']['sulu.lo/de'] = new PortalInformation(
            1,
            $webspaceRefs['sulu_io'],
            $portalRefs['sulu_io'],
            $localizationRefs['sulu_io_de'],
            'sulu.lo/de',
            null,
            null,
            null,
            true,
            'sulu.lo/{localization}',
            10
        );

        $portalInformationRefs['prod']['sulu.lo'] = new PortalInformation(
            2,
            $webspaceRefs['sulu_io'],
            $portalRefs['sulu_io'],
            null,
            'sulu.lo',
            null,
            'sulu.lo/{localization}',
            null,
            false,
            'sulu.lo/{localization}',
            9
        );

        $portalInformationRefs['stage']['sulu.lo/en'] = new PortalInformation(
            1,
            $webspaceRefs['sulu_io'],
            $portalRefs['sulu_io'],
            $localizationRefs['sulu_io_en'],
            'sulu.lo/en',
            null,
            null,
            null,
            true,
            'sulu.lo/{localization}',
            10
        );

        $portalInformationRefs['stage']['sulu.lo/de'] = new PortalInformation(
            1,
            $webspaceRefs['sulu_io'],
            $portalRefs['sulu_io'],
            $localizationRefs['sulu_io_de'],
            'sulu.lo/de',
            null,
            null,
            null,
            true,
            'sulu.lo/{localization}',
            10
        );

        $portalInformationRefs['stage']['sulu.lo'] = new PortalInformation(
            2,
            $webspaceRefs['sulu_io'],
            $portalRefs['sulu_io'],
            null,
            'sulu.lo',
            null,
            'sulu.lo/{localization}',
            null,
            false,
            'sulu.lo/{localization}',
            9
        );

        $portalInformationRefs['dev']['sulu.lo/en'] = new PortalInformation(
            1,
            $webspaceRefs['sulu_io'],
            $portalRefs['sulu_io'],
            $localizationRefs['sulu_io_en'],
            'sulu.lo/en',
            null,
            null,
            null,
            true,
            'sulu.lo/{localization}',
            10
        );

        $portalInformationRefs['dev']['sulu.lo/de'] = new PortalInformation(
            1,
            $webspaceRefs['sulu_io'],
            $portalRefs['sulu_io'],
            $localizationRefs['sulu_io_de'],
            'sulu.lo/de',
            null,
            null,
            null,
            true,
            'sulu.lo/{localization}',
            10
        );

        $portalInformationRefs['dev']['sulu.lo'] = new PortalInformation(
            2,
            $webspaceRefs['sulu_io'],
            $portalRefs['sulu_io'],
            null,
            'sulu.lo',
            null,
            'sulu.lo/{localization}',
            null,
            false,
            'sulu.lo/{localization}',
            9
        );


        $this->setWebspaces($webspaceRefs);
        $this->setPortals($portalRefs);
        $this->setPortalInformations($portalInformationRefs);
    }
}


